/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package email.service;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.ApplicationPidFileWriter;
import org.springframework.context.annotation.Import;
import org.springframework.context.annotation.PropertySource;
import org.springframework.scheduling.annotation.EnableAsync;

import email.service.config.MailConfig;
import email.service.config.YmlPropertySourceFactory;

@SpringBootApplication
@EnableAsync
@Import({ MailConfig.class})
@PropertySource({ "application.properties", "undertow.properties" })
@PropertySource(value = { "api_key.yml" }, factory = YmlPropertySourceFactory.class)
public class WebApplication {

    public static void main(String[] args) {
        SpringApplication application = new SpringApplication(WebApplication.class);
        application.addListeners(new ApplicationPidFileWriter());
        application.run(args);
    }

}
